name: bench

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bench:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: yarn
      - run: yarn install --immutable
      - run: yarn bench
